# Общие настройки для всех хостов
common_user: "deploy_user"
common_group: "deploy_group"

# Параметры для проверки сервиса
service_name: "nginx"

# Интервал проверки статуса сервиса в минутах
service_check_interval: 5

# Здесь указать путь до папки с логами
log_file: "/logs/service_check.log"

# Параметры для архивации логов
log_dirs:
  - "/opt/log/service_log/accounting"
  - "/opt/log/service_log/authoriz"
  - "/opt/log/service_log/authentic"
archive_dir: "/opt/log/archive"
# Дата для архивирования
archive_before_date: "2022-06-30 23:59:59"

# Настройки для уведомлений
email_recipient: "email@example.com" #  задать адрес электронной почты получателя уведомлений
smtp_host: "smtp.example.com"  # Здесь указать рабочий SMTP сервер