---
- name: Проверка и управление сервисом Nginx
  hosts: webservers
  become: yes
  vars:
    service_name: nginx
    log_file: /var/log/service_check.log
    email_recipient: email@example.com # сюда надо прописать нужный email

  tasks:
    - name: Проверка статуса сервиса
      command: systemctl is-active {{ service_name }}
      register: service_status
      ignore_errors: yes

    - name: Запись статуса в логфайл
      lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }}: {{ 'OK' if service_status.rc == 0 else 'Сервис недоступен' }}"

    - name: Запуск сервиса, если он недоступен
      systemd:
        name: "{{ service_name }}"
        state: started
      when: service_status.rc != 0
      register: start_service

    - name: Запись результата запуска в логфайл
      lineinfile:
        path: "{{ log_file }}"
        line: "{{ ansible_date_time.iso8601 }}: Сервис успешно запущен"
      when: start_service.changed

    - name: Проверка статуса сервиса после запуска
      command: systemctl is-active {{ service_name }}
      register: new_service_status
      when: start_service.changed

    - name: Отправка уведомления по электронной почте, если сервис все еще недоступен
      mail:
        host: localhost  # Замените на ваш SMTP-сервер
        to: "{{ email_recipient }}"
        subject: "Проблема с сервисом {{ service_name }}"
        body: "{{ ansible_date_time.iso8601 }}: {{ service_name }} {{ 'недоступен' if new_service_status.rc != 0 else 'доступен' }}"
      when: new_service_status.rc != 0